name: setup node
description: setup node.js environment

inputs:
  node-version:
    description: node version
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: install
      shell: bash
      run: npm ci
