name: checkout
description: checkout

runs:
  using: composite
  steps:
    - name: Get commit SHA
      id: sha
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"
        else
          echo "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.sha.outputs.sha }}
        fetch-depth: 2
