name: Commitlint

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run
        run: npx commitlint --from=HEAD~1 --to=HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
